{% set name = "anaconda-ident" %}
{% set version = "0.6.1" %}
{% set sha256 = "d1891bc24cefc2d0449c93d35fa89d10f9c01093bddbca3d59595a45946f2379" %}
{% set number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/anaconda/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ number }}
  entry_points:
    - anaconda-ident = anaconda_ident.install:main
    - anaconda-keymgr = anaconda_ident.keymgr:main
    - anaconda-heartbeat = anaconda_ident.heartbeat:main
    - anaconda-ident-hash = anaconda_ident.tokens:main

requirements:
  build:
    - git # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - conda >=23.7.1
    - anaconda-anon-usage >=0.7.3,<1
  run_constrained:
    - anaconda_client >=1.13.1

test:
  requires:
    - pip
    - proxyspy
  source_files:
    - tests/
  commands:
    - pip check
    - if not exist %CONDA_PREFIX%\\etc\\conda\\activate.d\\anaconda-ident_activate.bat exit 1  # [win]
    - if not exist %CONDA_PREFIX%\\Scripts\\.anaconda-ident-pre-unlink.bat exit 1  # [win]
    - if not exist %CONDA_PREFIX%\\Scripts\\.anaconda-ident-post-link.bat exit 1  # [win]
    - if [ ! -f $CONDA_PREFIX/etc/conda/activate.d/anaconda-ident_activate.sh ]; then exit 1; fi  # [unix]
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-pre-unlink.sh ]; then exit 1; fi  # [unix]
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-post-link.sh ]; then exit 1; fi  # [unix]
    - export ANACONDA_IDENT_DEBUG=1  # [unix]
    - export PYTHONUNBUFFERED=1  # [unix]
    - set ANACONDA_IDENT_DEBUG=1  # [win]
    - set PYTHONUNBUFFERED=1  # [win]
    - anaconda-ident --expect
    - conda create -n testchild1 --yes
    - conda create -n testchild2 --yes
    - conda info
    - conda info --envs
    - anaconda-keymgr --help
    - anaconda-ident-hash --help
    - python tests/test_config.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-ident
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/Anaconda-Platform/anaconda-ident/blob/main/LICENSE
  summary: simple, opt-in user identification for conda clients
  description: |
    The anaconda-ident package reconfigures conda to deliver a configurable amount
    of additional telemetry data when requesting indices and packages from a server.
  doc_url: https://github.com/Anaconda-Platform/anaconda-ident/blob/main/README.md
  dev_url: https://github.com/Anaconda-Platform/anaconda-ident

extra:
  recipe-maintainers:
    - mcg1969
